### ISSUE TITLE
有关self.dct_h和self.dct_w的设置？

### ISSUE THREAD

**Issue by XFR1998** [cfzd/FcaNet#10]
在这个类中MultiSpectralAttentionLayer有以下部分。
        if h != self.dct_h or w != self.dct_w:
            x_pooled = torch.nn.functional.adaptive_avg_pool2d(x, (self.dct_h, self.dct_w))
            # If you have concerns about one-line-change, don't worry.   :)
            # In the ImageNet models, this line will never be triggered.
            # This is for compatibility in instance segmentation and object detection.

如果我的任务是目标检测，我该怎么设置self.dct_h和self.dct_w？

**Comment by cfzd** [comment]
@XFR1998 
这个不需要设置，直接使用默认设置就好了。我们的默认设置是，以resnet为例，它的四个stage的dct_h分别为56,28,14,7，dct_w也是一样的. 具体代码可以看这块：
https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/fcanet.py#L19
https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/fcanet.py#L29

**Comment by XFR1998** [comment]
那如果我换成别的网络不用resnet我应该怎么根据实际情况设置呢？

**Comment by XFR1998** [comment]
我看你好像是根据通道数进行设置的对吗，应该怎么修改呢？谢谢

**Comment by cfzd** [comment]
那我觉得你就干脆全部设成7就行了。

**Comment by XFR1998** [comment]
> 那我觉得你就干脆全部设成7就行了。

好的谢谢大佬指点~

**Comment by Max-Well-Wang** [comment]
> 
> 
> > 那我觉得你就干脆全部设成7就行了。
> 
> 好的谢谢大佬指点~
我觉得需要重新设置c2wh = dict([(64,56), (128,28), (256,14) ,(512,7)])，根据通道及其对应的尺寸来改变。
