### ISSUE TITLE
代码好像和论文里说的不太一样也？

### ISSUE THREAD

**Issue by XFR1998** [cfzd/FcaNet#11]
不是只要修改一行吗，怎么里面还要设置这么多参数

**Comment by cfzd** [comment]
@XFR1998 
开源代码和论文里的代码是**完全等价**的，只不过为了大家使用方便，同时兼容更多的实验，我们开源的时候做了很多封装和脚手架代码。你可以对比一下以下代码和论文代码：
https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/layer.py#L78
https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/layer.py#L91-L98
