### ISSUE TITLE
launch.py: error: argument --nproc_per_node: invalid int value: ''

### ISSUE THREAD

**Issue by InukKang** [cfzd/FcaNet#12]
![image](https://user-images.githubusercontent.com/69806620/113763911-dcba4380-96df-11eb-8922-e10c3ba39d98.png)

I am running training data. but got this error. do you know how to deal with?

**Comment by cfzd** [comment]
@InukKang 
Hi, how many GPUs do you have? You can also try to set the number of GPUs manually:
```
python -m torch.distributed.launch --nproc_per_node=4 main.py -a fcanet50 --dali_cpu --b 64 /path/to/your/ImageNet
```
The `--nproc_per_node=4` set `nproc_per_node` to 4.

**Comment by InukKang** [comment]
Thank you!
