### ISSUE TITLE
关于split成n份的目的

### ISSUE THREAD

**Issue by HHCorp** [cfzd/FcaNet#14]
你好，我想请教关于split的问题。论文里说将输入channels分成n个部分来分别应用不同频率的DCTfilter，这里分成n个部分是出于什么目的？为什么不是对所有channels都应用一遍不同的DCTfilter？是出于计算量的考虑吗？

**Comment by cfzd** [comment]
@HHCorp 
是的，如果每个channel都做多遍的DCT pool的话，那个计算量就是多倍了。为了和SENet保持一样的计算量，我们选择了划分channel的方法

**Comment by HHCorp** [comment]
@cfzd 好的，谢谢解惑。您的工作还是非常有启发的。顺便追问下，对每个channel进行多遍不同dct filter虽然增加了计算量，但是否能带来些许效果上的提升？我感觉增加的计算量并没到会影响性能的程度。有做过相关的实验吗？

**Comment by cfzd** [comment]
@HHCorp 
这个我们确实没有做过实验，我觉得直觉上应该是可以提升一部分效果的。

**Comment by HHCorp** [comment]
@cfzd 哦哦，感谢答疑
