### ISSUE TITLE
关于math.sqrt(POS)

### ISSUE THREAD

**Issue by Asthestarsfalll** [cfzd/FcaNet#15]
您好，感谢您的代码。
请问这里的除以根号和乘以根号是起到类似求平均的作用吗？
![image](https://user-images.githubusercontent.com/72954905/128623102-502996c0-ad93-4b3f-9592-e5da205381ea.png)
为什么不直接在空间维度求和时直接进行.mean()呢

**Comment by cfzd** [comment]
@Asthestarsfalll 
这个其实是DCT基函数的定义，在文章中我们为了简化起见去掉了这些缩放因子。可能直接去掉或者求mean也可以，我们这个地方保持了和一般的DCT一样的运算。

**Comment by Asthestarsfalll** [comment]
@cfzd 
好的，感谢您的回答。
另外请问是否能分享论文中进行单个频率分量实验时的预训练模型和代码，我对此有些思考，想进行下对比实验。
再次感谢您。

**Comment by cfzd** [comment]
@Asthestarsfalll 
如果想进行单个频率分量实验的话，可以简单的override以下这个函数：
https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/layer.py#L5-L27

例如我只想以第0个或第9个频率做实验，那么我只需修改上述函数为：
```
return [0], [0] # for 0th freq
return [1], [2] # for 9th freq
```

关于模型的问题，因为总共有49个模型，不是特别容易分享，我可能需要打包上传到Google drive再分享给你。

PS 我们最近也遇到一个新的问题，就是现在论文中单个频率的实验可能会涉及到验证集的问题，我们已经重新跑了这个实验了（重新划分了train和val，并且不涉及原来imagenet的验证集），而且论文也会一并修改掉，我后续上传模型的也应该是这个setting下的。

**Comment by Asthestarsfalll** [comment]
@cfzd 
感谢，49个模型上传过于麻烦，可以只分享文中提到的100个epoch的base model吗？
祝你们实验顺利！

**Comment by peterzpy** [comment]
@Asthestarsfalll 

您好，我们的base model直接使用的是pytorch官方提供的预训练模型，在单个频域分量上训练时使用0.02的学习率，对整个模型finetune20个epoch。

**Comment by Asthestarsfalll** [comment]
@peterzpy 好的，非常感谢！
