### ISSUE TITLE
不大一致

### ISSUE THREAD

**Issue by desertfex** [cfzd/FcaNet#2]
在layer.py中有：
class MultiSpectralAttentionLayer(torch.nn.Module):中有
self.dct_layer = MultiSpectralDCTLayer(dct_h, dct_w, mapper_x, mapper_y, channel) 
可见dct_h在前， dct_w在后 就是h在前，w在后
而在class MultiSpectralDCTLayer(nn.Module):中
def __init__(self, width, height, mapper_x, mapper_y, channel): 
可见 width在前，height在后，就是w在前，h在后
请问这有什么说处么？我晕了

**Comment by cfzd** [comment]
@desertfex 
这个是一个typo，我们已经在新的commit里fix了。实际上这个typo也不影响结果，因为ImageNet上宽和高都是一样的。
