### ISSUE TITLE
What's the difference between FcaBottleneck and FcaBasicBlock ? 

### ISSUE THREAD

**Issue by meiguoofa** [cfzd/FcaNet#23]
As in your code, the FcaBottleneck expansion is 4 and FcaBasicBlock  is 1, FcaBottleneck has one more layer of convolution than FcaBasicBlock, so how should I choose which module to use ?

**Comment by meiguoofa** [comment]
and if i want to input a feature dim = 32 or 16, How should I set the wh?

**Comment by cfzd** [comment]
@meiguoofa 
The story is:
ResNet has two kinds of blocks, which are `Bottleneck` and `BasicBlock`. `Bottleneck`s are used in large models like Res50, 101, 152. `BasicBlocks` are used in Res34 and Res18.

When they are combined with our attention method, it becomes `FcaBottleneck` and `FcaBasicBlock`.  If you want to use our work, just use the defined `fcanet34`, `fcanet50` functions to get the model.

If you have a feature dim like 32 or 16, just add an item in here:

https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/fcanet.py#L19
like:
```
 c2wh = dict([(64,56), (128,28), (256,14) ,(512,7),  (32,112), (16, 224) ])
```

In this case, I set the size to 112 and 224 for 32 and 16 dim respectively. You can set it as you want.

**Comment by meiguoofa** [comment]
Thank You! your answer helped me a lot.
