### ISSUE TITLE
关于模型精度

### ISSUE THREAD

**Issue by 123456789asdfjkl** [cfzd/FcaNet#38]
您好，非常感谢您的杰出工作，我使用了您的代码和模型在imagenet上FcaNet50得到的验证集准确率为78.39，请问是正常的吗，环境是Ubuntu20.04，cuda11.6，pytorch1.10，4卡3090，期待您的回复

**Comment by cfzd** [comment]
@123456789asdfjkl 
训练模型是会有的一定的波动的，不过这个结果和我们的结果几乎一样的。

**Comment by 123456789asdfjkl** [comment]
非常感谢您的回复
