### ISSUE TITLE
get_freq_indices

### ISSUE THREAD

**Issue by Slayerxxx** [cfzd/FcaNet#4]
您好，请问下get_freq_indices这个函数中那些indices数组是什么作用阿，没太看懂其中规律。
感谢！

**Comment by cfzd** [comment]
@Slayerxxx 
您好，indices数组存储的选择不同频率方法的坐标。我们给出了几种可能的选择方案，包括选高性能top-k，选低频low-k，选低性能bot-k。具体的含义也可以参考[我们文章](https://arxiv.org/pdf/2012.11879.pdf)的Fig. 4和附录6.1里的内容。

**Comment by Slayerxxx** [comment]
@cfzd 
那top和bot都是经验值吗？

**Comment by Slayerxxx** [comment]
谢谢明白了
