### ISSUE TITLE
get_freq_indices?

### ISSUE THREAD

**Issue by qiuqiu-lwf** [cfzd/FcaNet#8]
Hello, could you please tell me how to calculate the indices of the three methods in the code?thank you！

**Comment by emergencyd** [comment]
@qiuqiu-lwf do you know how? I'm trying to modify this to 3D. Thank you!

**Comment by Asthestarsfalll** [comment]
> @qiuqiu-lwf do you know how? I'm trying to modify this to 3D. Thank you!

In the section 4.2, Top-1 accuracies on ImageNet using different frequency components in channel attention individually. the indices are based on this.
